server:
  port: 9080
  servlet:
    context-path: /wms-core
    
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.shanhe.springboot.entity
    
spring:
  profiles:
    active: secret
  servlet:
    multipart:
      maxFileSize: 200MB
      maxRequestSize: 200MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM dual
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    database: 0 #Redis数据库索引(默认为0)
    host: 118.25.84.80
    port: 6379
    password: 123456
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0
      timeout: 1000
    
druid:
  stat:
   slowSqlMillis: 20      
   
   