package com.hht.wms.core.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FrontDeskChargeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table front_desk_charge
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table front_desk_charge
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table front_desk_charge
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     *  构造查询条件,front_desk_charge
     */
    public FrontDeskChargeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,front_desk_charge
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,front_desk_charge
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,front_desk_charge
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,front_desk_charge
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,front_desk_charge
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,front_desk_charge
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,front_desk_charge
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,front_desk_charge
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,front_desk_charge
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,front_desk_charge
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * 
     * GeneratedCriteria
     * 数据库表：front_desk_charge
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andInboundNoIsNull() {
            addCriterion("inbound_no is null");
            return (Criteria) this;
        }

        public Criteria andInboundNoIsNotNull() {
            addCriterion("inbound_no is not null");
            return (Criteria) this;
        }

        public Criteria andInboundNoEqualTo(String value) {
            addCriterion("inbound_no =", value, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoNotEqualTo(String value) {
            addCriterion("inbound_no <>", value, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoGreaterThan(String value) {
            addCriterion("inbound_no >", value, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoGreaterThanOrEqualTo(String value) {
            addCriterion("inbound_no >=", value, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoLessThan(String value) {
            addCriterion("inbound_no <", value, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoLessThanOrEqualTo(String value) {
            addCriterion("inbound_no <=", value, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoLike(String value) {
            addCriterion("inbound_no like", value, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoNotLike(String value) {
            addCriterion("inbound_no not like", value, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoIn(List<String> values) {
            addCriterion("inbound_no in", values, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoNotIn(List<String> values) {
            addCriterion("inbound_no not in", values, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoBetween(String value1, String value2) {
            addCriterion("inbound_no between", value1, value2, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoNotBetween(String value1, String value2) {
            addCriterion("inbound_no not between", value1, value2, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNull() {
            addCriterion("cust_name is null");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNotNull() {
            addCriterion("cust_name is not null");
            return (Criteria) this;
        }

        public Criteria andCustNameEqualTo(String value) {
            addCriterion("cust_name =", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotEqualTo(String value) {
            addCriterion("cust_name <>", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThan(String value) {
            addCriterion("cust_name >", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThanOrEqualTo(String value) {
            addCriterion("cust_name >=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThan(String value) {
            addCriterion("cust_name <", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThanOrEqualTo(String value) {
            addCriterion("cust_name <=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLike(String value) {
            addCriterion("cust_name like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotLike(String value) {
            addCriterion("cust_name not like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameIn(List<String> values) {
            addCriterion("cust_name in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotIn(List<String> values) {
            addCriterion("cust_name not in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameBetween(String value1, String value2) {
            addCriterion("cust_name between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotBetween(String value1, String value2) {
            addCriterion("cust_name not between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNull() {
            addCriterion("project_name is null");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNotNull() {
            addCriterion("project_name is not null");
            return (Criteria) this;
        }

        public Criteria andProjectNameEqualTo(String value) {
            addCriterion("project_name =", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotEqualTo(String value) {
            addCriterion("project_name <>", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThan(String value) {
            addCriterion("project_name >", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("project_name >=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThan(String value) {
            addCriterion("project_name <", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThanOrEqualTo(String value) {
            addCriterion("project_name <=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLike(String value) {
            addCriterion("project_name like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotLike(String value) {
            addCriterion("project_name not like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameIn(List<String> values) {
            addCriterion("project_name in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotIn(List<String> values) {
            addCriterion("project_name not in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameBetween(String value1, String value2) {
            addCriterion("project_name between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotBetween(String value1, String value2) {
            addCriterion("project_name not between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andPlateNumIsNull() {
            addCriterion("plate_num is null");
            return (Criteria) this;
        }

        public Criteria andPlateNumIsNotNull() {
            addCriterion("plate_num is not null");
            return (Criteria) this;
        }

        public Criteria andPlateNumEqualTo(String value) {
            addCriterion("plate_num =", value, "plateNum");
            return (Criteria) this;
        }

        public Criteria andPlateNumNotEqualTo(String value) {
            addCriterion("plate_num <>", value, "plateNum");
            return (Criteria) this;
        }

        public Criteria andPlateNumGreaterThan(String value) {
            addCriterion("plate_num >", value, "plateNum");
            return (Criteria) this;
        }

        public Criteria andPlateNumGreaterThanOrEqualTo(String value) {
            addCriterion("plate_num >=", value, "plateNum");
            return (Criteria) this;
        }

        public Criteria andPlateNumLessThan(String value) {
            addCriterion("plate_num <", value, "plateNum");
            return (Criteria) this;
        }

        public Criteria andPlateNumLessThanOrEqualTo(String value) {
            addCriterion("plate_num <=", value, "plateNum");
            return (Criteria) this;
        }

        public Criteria andPlateNumLike(String value) {
            addCriterion("plate_num like", value, "plateNum");
            return (Criteria) this;
        }

        public Criteria andPlateNumNotLike(String value) {
            addCriterion("plate_num not like", value, "plateNum");
            return (Criteria) this;
        }

        public Criteria andPlateNumIn(List<String> values) {
            addCriterion("plate_num in", values, "plateNum");
            return (Criteria) this;
        }

        public Criteria andPlateNumNotIn(List<String> values) {
            addCriterion("plate_num not in", values, "plateNum");
            return (Criteria) this;
        }

        public Criteria andPlateNumBetween(String value1, String value2) {
            addCriterion("plate_num between", value1, value2, "plateNum");
            return (Criteria) this;
        }

        public Criteria andPlateNumNotBetween(String value1, String value2) {
            addCriterion("plate_num not between", value1, value2, "plateNum");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeIsNull() {
            addCriterion("settlement_type is null");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeIsNotNull() {
            addCriterion("settlement_type is not null");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeEqualTo(String value) {
            addCriterion("settlement_type =", value, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeNotEqualTo(String value) {
            addCriterion("settlement_type <>", value, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeGreaterThan(String value) {
            addCriterion("settlement_type >", value, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeGreaterThanOrEqualTo(String value) {
            addCriterion("settlement_type >=", value, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeLessThan(String value) {
            addCriterion("settlement_type <", value, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeLessThanOrEqualTo(String value) {
            addCriterion("settlement_type <=", value, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeLike(String value) {
            addCriterion("settlement_type like", value, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeNotLike(String value) {
            addCriterion("settlement_type not like", value, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeIn(List<String> values) {
            addCriterion("settlement_type in", values, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeNotIn(List<String> values) {
            addCriterion("settlement_type not in", values, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeBetween(String value1, String value2) {
            addCriterion("settlement_type between", value1, value2, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeNotBetween(String value1, String value2) {
            addCriterion("settlement_type not between", value1, value2, "settlementType");
            return (Criteria) this;
        }

        public Criteria andEnterGateFeeIsNull() {
            addCriterion("enter_gate_fee is null");
            return (Criteria) this;
        }

        public Criteria andEnterGateFeeIsNotNull() {
            addCriterion("enter_gate_fee is not null");
            return (Criteria) this;
        }

        public Criteria andEnterGateFeeEqualTo(BigDecimal value) {
            addCriterion("enter_gate_fee =", value, "enterGateFee");
            return (Criteria) this;
        }

        public Criteria andEnterGateFeeNotEqualTo(BigDecimal value) {
            addCriterion("enter_gate_fee <>", value, "enterGateFee");
            return (Criteria) this;
        }

        public Criteria andEnterGateFeeGreaterThan(BigDecimal value) {
            addCriterion("enter_gate_fee >", value, "enterGateFee");
            return (Criteria) this;
        }

        public Criteria andEnterGateFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("enter_gate_fee >=", value, "enterGateFee");
            return (Criteria) this;
        }

        public Criteria andEnterGateFeeLessThan(BigDecimal value) {
            addCriterion("enter_gate_fee <", value, "enterGateFee");
            return (Criteria) this;
        }

        public Criteria andEnterGateFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("enter_gate_fee <=", value, "enterGateFee");
            return (Criteria) this;
        }

        public Criteria andEnterGateFeeIn(List<BigDecimal> values) {
            addCriterion("enter_gate_fee in", values, "enterGateFee");
            return (Criteria) this;
        }

        public Criteria andEnterGateFeeNotIn(List<BigDecimal> values) {
            addCriterion("enter_gate_fee not in", values, "enterGateFee");
            return (Criteria) this;
        }

        public Criteria andEnterGateFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("enter_gate_fee between", value1, value2, "enterGateFee");
            return (Criteria) this;
        }

        public Criteria andEnterGateFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("enter_gate_fee not between", value1, value2, "enterGateFee");
            return (Criteria) this;
        }

        public Criteria andCustomsDeclarationFeeIsNull() {
            addCriterion("customs_declaration_fee is null");
            return (Criteria) this;
        }

        public Criteria andCustomsDeclarationFeeIsNotNull() {
            addCriterion("customs_declaration_fee is not null");
            return (Criteria) this;
        }

        public Criteria andCustomsDeclarationFeeEqualTo(BigDecimal value) {
            addCriterion("customs_declaration_fee =", value, "customsDeclarationFee");
            return (Criteria) this;
        }

        public Criteria andCustomsDeclarationFeeNotEqualTo(BigDecimal value) {
            addCriterion("customs_declaration_fee <>", value, "customsDeclarationFee");
            return (Criteria) this;
        }

        public Criteria andCustomsDeclarationFeeGreaterThan(BigDecimal value) {
            addCriterion("customs_declaration_fee >", value, "customsDeclarationFee");
            return (Criteria) this;
        }

        public Criteria andCustomsDeclarationFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("customs_declaration_fee >=", value, "customsDeclarationFee");
            return (Criteria) this;
        }

        public Criteria andCustomsDeclarationFeeLessThan(BigDecimal value) {
            addCriterion("customs_declaration_fee <", value, "customsDeclarationFee");
            return (Criteria) this;
        }

        public Criteria andCustomsDeclarationFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("customs_declaration_fee <=", value, "customsDeclarationFee");
            return (Criteria) this;
        }

        public Criteria andCustomsDeclarationFeeIn(List<BigDecimal> values) {
            addCriterion("customs_declaration_fee in", values, "customsDeclarationFee");
            return (Criteria) this;
        }

        public Criteria andCustomsDeclarationFeeNotIn(List<BigDecimal> values) {
            addCriterion("customs_declaration_fee not in", values, "customsDeclarationFee");
            return (Criteria) this;
        }

        public Criteria andCustomsDeclarationFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("customs_declaration_fee between", value1, value2, "customsDeclarationFee");
            return (Criteria) this;
        }

        public Criteria andCustomsDeclarationFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("customs_declaration_fee not between", value1, value2, "customsDeclarationFee");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("create_date like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("create_date not like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<String> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<String> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：front_desk_charge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 
     * Criterion
     * 数据库表：front_desk_charge
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}