package com.hht.wms.core.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ShippedInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shipped_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shipped_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shipped_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     *  构造查询条件,shipped_info
     */
    public ShippedInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,shipped_info
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,shipped_info
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,shipped_info
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,shipped_info
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,shipped_info
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,shipped_info
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,shipped_info
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,shipped_info
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,shipped_info
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,shipped_info
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * 
     * GeneratedCriteria
     * 数据库表：shipped_info
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSoIsNull() {
            addCriterion("so is null");
            return (Criteria) this;
        }

        public Criteria andSoIsNotNull() {
            addCriterion("so is not null");
            return (Criteria) this;
        }

        public Criteria andSoEqualTo(String value) {
            addCriterion("so =", value, "so");
            return (Criteria) this;
        }

        public Criteria andSoNotEqualTo(String value) {
            addCriterion("so <>", value, "so");
            return (Criteria) this;
        }

        public Criteria andSoGreaterThan(String value) {
            addCriterion("so >", value, "so");
            return (Criteria) this;
        }

        public Criteria andSoGreaterThanOrEqualTo(String value) {
            addCriterion("so >=", value, "so");
            return (Criteria) this;
        }

        public Criteria andSoLessThan(String value) {
            addCriterion("so <", value, "so");
            return (Criteria) this;
        }

        public Criteria andSoLessThanOrEqualTo(String value) {
            addCriterion("so <=", value, "so");
            return (Criteria) this;
        }

        public Criteria andSoLike(String value) {
            addCriterion("so like", value, "so");
            return (Criteria) this;
        }

        public Criteria andSoNotLike(String value) {
            addCriterion("so not like", value, "so");
            return (Criteria) this;
        }

        public Criteria andSoIn(List<String> values) {
            addCriterion("so in", values, "so");
            return (Criteria) this;
        }

        public Criteria andSoNotIn(List<String> values) {
            addCriterion("so not in", values, "so");
            return (Criteria) this;
        }

        public Criteria andSoBetween(String value1, String value2) {
            addCriterion("so between", value1, value2, "so");
            return (Criteria) this;
        }

        public Criteria andSoNotBetween(String value1, String value2) {
            addCriterion("so not between", value1, value2, "so");
            return (Criteria) this;
        }

        public Criteria andPoIsNull() {
            addCriterion("po is null");
            return (Criteria) this;
        }

        public Criteria andPoIsNotNull() {
            addCriterion("po is not null");
            return (Criteria) this;
        }

        public Criteria andPoEqualTo(String value) {
            addCriterion("po =", value, "po");
            return (Criteria) this;
        }

        public Criteria andPoNotEqualTo(String value) {
            addCriterion("po <>", value, "po");
            return (Criteria) this;
        }

        public Criteria andPoGreaterThan(String value) {
            addCriterion("po >", value, "po");
            return (Criteria) this;
        }

        public Criteria andPoGreaterThanOrEqualTo(String value) {
            addCriterion("po >=", value, "po");
            return (Criteria) this;
        }

        public Criteria andPoLessThan(String value) {
            addCriterion("po <", value, "po");
            return (Criteria) this;
        }

        public Criteria andPoLessThanOrEqualTo(String value) {
            addCriterion("po <=", value, "po");
            return (Criteria) this;
        }

        public Criteria andPoLike(String value) {
            addCriterion("po like", value, "po");
            return (Criteria) this;
        }

        public Criteria andPoNotLike(String value) {
            addCriterion("po not like", value, "po");
            return (Criteria) this;
        }

        public Criteria andPoIn(List<String> values) {
            addCriterion("po in", values, "po");
            return (Criteria) this;
        }

        public Criteria andPoNotIn(List<String> values) {
            addCriterion("po not in", values, "po");
            return (Criteria) this;
        }

        public Criteria andPoBetween(String value1, String value2) {
            addCriterion("po between", value1, value2, "po");
            return (Criteria) this;
        }

        public Criteria andPoNotBetween(String value1, String value2) {
            addCriterion("po not between", value1, value2, "po");
            return (Criteria) this;
        }

        public Criteria andSkuIsNull() {
            addCriterion("sku is null");
            return (Criteria) this;
        }

        public Criteria andSkuIsNotNull() {
            addCriterion("sku is not null");
            return (Criteria) this;
        }

        public Criteria andSkuEqualTo(String value) {
            addCriterion("sku =", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuNotEqualTo(String value) {
            addCriterion("sku <>", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuGreaterThan(String value) {
            addCriterion("sku >", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuGreaterThanOrEqualTo(String value) {
            addCriterion("sku >=", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuLessThan(String value) {
            addCriterion("sku <", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuLessThanOrEqualTo(String value) {
            addCriterion("sku <=", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuLike(String value) {
            addCriterion("sku like", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuNotLike(String value) {
            addCriterion("sku not like", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuIn(List<String> values) {
            addCriterion("sku in", values, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuNotIn(List<String> values) {
            addCriterion("sku not in", values, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuBetween(String value1, String value2) {
            addCriterion("sku between", value1, value2, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuNotBetween(String value1, String value2) {
            addCriterion("sku not between", value1, value2, "sku");
            return (Criteria) this;
        }

        public Criteria andInboundNoIsNull() {
            addCriterion("inbound_no is null");
            return (Criteria) this;
        }

        public Criteria andInboundNoIsNotNull() {
            addCriterion("inbound_no is not null");
            return (Criteria) this;
        }

        public Criteria andInboundNoEqualTo(String value) {
            addCriterion("inbound_no =", value, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoNotEqualTo(String value) {
            addCriterion("inbound_no <>", value, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoGreaterThan(String value) {
            addCriterion("inbound_no >", value, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoGreaterThanOrEqualTo(String value) {
            addCriterion("inbound_no >=", value, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoLessThan(String value) {
            addCriterion("inbound_no <", value, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoLessThanOrEqualTo(String value) {
            addCriterion("inbound_no <=", value, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoLike(String value) {
            addCriterion("inbound_no like", value, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoNotLike(String value) {
            addCriterion("inbound_no not like", value, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoIn(List<String> values) {
            addCriterion("inbound_no in", values, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoNotIn(List<String> values) {
            addCriterion("inbound_no not in", values, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoBetween(String value1, String value2) {
            addCriterion("inbound_no between", value1, value2, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andInboundNoNotBetween(String value1, String value2) {
            addCriterion("inbound_no not between", value1, value2, "inboundNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMeterialNoIsNull() {
            addCriterion("customs_meterial_no is null");
            return (Criteria) this;
        }

        public Criteria andCustomsMeterialNoIsNotNull() {
            addCriterion("customs_meterial_no is not null");
            return (Criteria) this;
        }

        public Criteria andCustomsMeterialNoEqualTo(String value) {
            addCriterion("customs_meterial_no =", value, "customsMeterialNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMeterialNoNotEqualTo(String value) {
            addCriterion("customs_meterial_no <>", value, "customsMeterialNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMeterialNoGreaterThan(String value) {
            addCriterion("customs_meterial_no >", value, "customsMeterialNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMeterialNoGreaterThanOrEqualTo(String value) {
            addCriterion("customs_meterial_no >=", value, "customsMeterialNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMeterialNoLessThan(String value) {
            addCriterion("customs_meterial_no <", value, "customsMeterialNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMeterialNoLessThanOrEqualTo(String value) {
            addCriterion("customs_meterial_no <=", value, "customsMeterialNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMeterialNoLike(String value) {
            addCriterion("customs_meterial_no like", value, "customsMeterialNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMeterialNoNotLike(String value) {
            addCriterion("customs_meterial_no not like", value, "customsMeterialNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMeterialNoIn(List<String> values) {
            addCriterion("customs_meterial_no in", values, "customsMeterialNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMeterialNoNotIn(List<String> values) {
            addCriterion("customs_meterial_no not in", values, "customsMeterialNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMeterialNoBetween(String value1, String value2) {
            addCriterion("customs_meterial_no between", value1, value2, "customsMeterialNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMeterialNoNotBetween(String value1, String value2) {
            addCriterion("customs_meterial_no not between", value1, value2, "customsMeterialNo");
            return (Criteria) this;
        }

        public Criteria andShippedOrderDateIsNull() {
            addCriterion("shipped_order_date is null");
            return (Criteria) this;
        }

        public Criteria andShippedOrderDateIsNotNull() {
            addCriterion("shipped_order_date is not null");
            return (Criteria) this;
        }

        public Criteria andShippedOrderDateEqualTo(String value) {
            addCriterion("shipped_order_date =", value, "shippedOrderDate");
            return (Criteria) this;
        }

        public Criteria andShippedOrderDateNotEqualTo(String value) {
            addCriterion("shipped_order_date <>", value, "shippedOrderDate");
            return (Criteria) this;
        }

        public Criteria andShippedOrderDateGreaterThan(String value) {
            addCriterion("shipped_order_date >", value, "shippedOrderDate");
            return (Criteria) this;
        }

        public Criteria andShippedOrderDateGreaterThanOrEqualTo(String value) {
            addCriterion("shipped_order_date >=", value, "shippedOrderDate");
            return (Criteria) this;
        }

        public Criteria andShippedOrderDateLessThan(String value) {
            addCriterion("shipped_order_date <", value, "shippedOrderDate");
            return (Criteria) this;
        }

        public Criteria andShippedOrderDateLessThanOrEqualTo(String value) {
            addCriterion("shipped_order_date <=", value, "shippedOrderDate");
            return (Criteria) this;
        }

        public Criteria andShippedOrderDateLike(String value) {
            addCriterion("shipped_order_date like", value, "shippedOrderDate");
            return (Criteria) this;
        }

        public Criteria andShippedOrderDateNotLike(String value) {
            addCriterion("shipped_order_date not like", value, "shippedOrderDate");
            return (Criteria) this;
        }

        public Criteria andShippedOrderDateIn(List<String> values) {
            addCriterion("shipped_order_date in", values, "shippedOrderDate");
            return (Criteria) this;
        }

        public Criteria andShippedOrderDateNotIn(List<String> values) {
            addCriterion("shipped_order_date not in", values, "shippedOrderDate");
            return (Criteria) this;
        }

        public Criteria andShippedOrderDateBetween(String value1, String value2) {
            addCriterion("shipped_order_date between", value1, value2, "shippedOrderDate");
            return (Criteria) this;
        }

        public Criteria andShippedOrderDateNotBetween(String value1, String value2) {
            addCriterion("shipped_order_date not between", value1, value2, "shippedOrderDate");
            return (Criteria) this;
        }

        public Criteria andShippedDateIsNull() {
            addCriterion("shipped_date is null");
            return (Criteria) this;
        }

        public Criteria andShippedDateIsNotNull() {
            addCriterion("shipped_date is not null");
            return (Criteria) this;
        }

        public Criteria andShippedDateEqualTo(String value) {
            addCriterion("shipped_date =", value, "shippedDate");
            return (Criteria) this;
        }

        public Criteria andShippedDateNotEqualTo(String value) {
            addCriterion("shipped_date <>", value, "shippedDate");
            return (Criteria) this;
        }

        public Criteria andShippedDateGreaterThan(String value) {
            addCriterion("shipped_date >", value, "shippedDate");
            return (Criteria) this;
        }

        public Criteria andShippedDateGreaterThanOrEqualTo(String value) {
            addCriterion("shipped_date >=", value, "shippedDate");
            return (Criteria) this;
        }

        public Criteria andShippedDateLessThan(String value) {
            addCriterion("shipped_date <", value, "shippedDate");
            return (Criteria) this;
        }

        public Criteria andShippedDateLessThanOrEqualTo(String value) {
            addCriterion("shipped_date <=", value, "shippedDate");
            return (Criteria) this;
        }

        public Criteria andShippedDateLike(String value) {
            addCriterion("shipped_date like", value, "shippedDate");
            return (Criteria) this;
        }

        public Criteria andShippedDateNotLike(String value) {
            addCriterion("shipped_date not like", value, "shippedDate");
            return (Criteria) this;
        }

        public Criteria andShippedDateIn(List<String> values) {
            addCriterion("shipped_date in", values, "shippedDate");
            return (Criteria) this;
        }

        public Criteria andShippedDateNotIn(List<String> values) {
            addCriterion("shipped_date not in", values, "shippedDate");
            return (Criteria) this;
        }

        public Criteria andShippedDateBetween(String value1, String value2) {
            addCriterion("shipped_date between", value1, value2, "shippedDate");
            return (Criteria) this;
        }

        public Criteria andShippedDateNotBetween(String value1, String value2) {
            addCriterion("shipped_date not between", value1, value2, "shippedDate");
            return (Criteria) this;
        }

        public Criteria andShippedNoIsNull() {
            addCriterion("shipped_no is null");
            return (Criteria) this;
        }

        public Criteria andShippedNoIsNotNull() {
            addCriterion("shipped_no is not null");
            return (Criteria) this;
        }

        public Criteria andShippedNoEqualTo(String value) {
            addCriterion("shipped_no =", value, "shippedNo");
            return (Criteria) this;
        }

        public Criteria andShippedNoNotEqualTo(String value) {
            addCriterion("shipped_no <>", value, "shippedNo");
            return (Criteria) this;
        }

        public Criteria andShippedNoGreaterThan(String value) {
            addCriterion("shipped_no >", value, "shippedNo");
            return (Criteria) this;
        }

        public Criteria andShippedNoGreaterThanOrEqualTo(String value) {
            addCriterion("shipped_no >=", value, "shippedNo");
            return (Criteria) this;
        }

        public Criteria andShippedNoLessThan(String value) {
            addCriterion("shipped_no <", value, "shippedNo");
            return (Criteria) this;
        }

        public Criteria andShippedNoLessThanOrEqualTo(String value) {
            addCriterion("shipped_no <=", value, "shippedNo");
            return (Criteria) this;
        }

        public Criteria andShippedNoLike(String value) {
            addCriterion("shipped_no like", value, "shippedNo");
            return (Criteria) this;
        }

        public Criteria andShippedNoNotLike(String value) {
            addCriterion("shipped_no not like", value, "shippedNo");
            return (Criteria) this;
        }

        public Criteria andShippedNoIn(List<String> values) {
            addCriterion("shipped_no in", values, "shippedNo");
            return (Criteria) this;
        }

        public Criteria andShippedNoNotIn(List<String> values) {
            addCriterion("shipped_no not in", values, "shippedNo");
            return (Criteria) this;
        }

        public Criteria andShippedNoBetween(String value1, String value2) {
            addCriterion("shipped_no between", value1, value2, "shippedNo");
            return (Criteria) this;
        }

        public Criteria andShippedNoNotBetween(String value1, String value2) {
            addCriterion("shipped_no not between", value1, value2, "shippedNo");
            return (Criteria) this;
        }

        public Criteria andWarehousePositionIsNull() {
            addCriterion("warehouse_position is null");
            return (Criteria) this;
        }

        public Criteria andWarehousePositionIsNotNull() {
            addCriterion("warehouse_position is not null");
            return (Criteria) this;
        }

        public Criteria andWarehousePositionEqualTo(String value) {
            addCriterion("warehouse_position =", value, "warehousePosition");
            return (Criteria) this;
        }

        public Criteria andWarehousePositionNotEqualTo(String value) {
            addCriterion("warehouse_position <>", value, "warehousePosition");
            return (Criteria) this;
        }

        public Criteria andWarehousePositionGreaterThan(String value) {
            addCriterion("warehouse_position >", value, "warehousePosition");
            return (Criteria) this;
        }

        public Criteria andWarehousePositionGreaterThanOrEqualTo(String value) {
            addCriterion("warehouse_position >=", value, "warehousePosition");
            return (Criteria) this;
        }

        public Criteria andWarehousePositionLessThan(String value) {
            addCriterion("warehouse_position <", value, "warehousePosition");
            return (Criteria) this;
        }

        public Criteria andWarehousePositionLessThanOrEqualTo(String value) {
            addCriterion("warehouse_position <=", value, "warehousePosition");
            return (Criteria) this;
        }

        public Criteria andWarehousePositionLike(String value) {
            addCriterion("warehouse_position like", value, "warehousePosition");
            return (Criteria) this;
        }

        public Criteria andWarehousePositionNotLike(String value) {
            addCriterion("warehouse_position not like", value, "warehousePosition");
            return (Criteria) this;
        }

        public Criteria andWarehousePositionIn(List<String> values) {
            addCriterion("warehouse_position in", values, "warehousePosition");
            return (Criteria) this;
        }

        public Criteria andWarehousePositionNotIn(List<String> values) {
            addCriterion("warehouse_position not in", values, "warehousePosition");
            return (Criteria) this;
        }

        public Criteria andWarehousePositionBetween(String value1, String value2) {
            addCriterion("warehouse_position between", value1, value2, "warehousePosition");
            return (Criteria) this;
        }

        public Criteria andWarehousePositionNotBetween(String value1, String value2) {
            addCriterion("warehouse_position not between", value1, value2, "warehousePosition");
            return (Criteria) this;
        }

        public Criteria andShippedCtnsIsNull() {
            addCriterion("shipped_ctns is null");
            return (Criteria) this;
        }

        public Criteria andShippedCtnsIsNotNull() {
            addCriterion("shipped_ctns is not null");
            return (Criteria) this;
        }

        public Criteria andShippedCtnsEqualTo(BigDecimal value) {
            addCriterion("shipped_ctns =", value, "shippedCtns");
            return (Criteria) this;
        }

        public Criteria andShippedCtnsNotEqualTo(BigDecimal value) {
            addCriterion("shipped_ctns <>", value, "shippedCtns");
            return (Criteria) this;
        }

        public Criteria andShippedCtnsGreaterThan(BigDecimal value) {
            addCriterion("shipped_ctns >", value, "shippedCtns");
            return (Criteria) this;
        }

        public Criteria andShippedCtnsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("shipped_ctns >=", value, "shippedCtns");
            return (Criteria) this;
        }

        public Criteria andShippedCtnsLessThan(BigDecimal value) {
            addCriterion("shipped_ctns <", value, "shippedCtns");
            return (Criteria) this;
        }

        public Criteria andShippedCtnsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("shipped_ctns <=", value, "shippedCtns");
            return (Criteria) this;
        }

        public Criteria andShippedCtnsIn(List<BigDecimal> values) {
            addCriterion("shipped_ctns in", values, "shippedCtns");
            return (Criteria) this;
        }

        public Criteria andShippedCtnsNotIn(List<BigDecimal> values) {
            addCriterion("shipped_ctns not in", values, "shippedCtns");
            return (Criteria) this;
        }

        public Criteria andShippedCtnsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shipped_ctns between", value1, value2, "shippedCtns");
            return (Criteria) this;
        }

        public Criteria andShippedCtnsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shipped_ctns not between", value1, value2, "shippedCtns");
            return (Criteria) this;
        }

        public Criteria andShippedPcsIsNull() {
            addCriterion("shipped_pcs is null");
            return (Criteria) this;
        }

        public Criteria andShippedPcsIsNotNull() {
            addCriterion("shipped_pcs is not null");
            return (Criteria) this;
        }

        public Criteria andShippedPcsEqualTo(Integer value) {
            addCriterion("shipped_pcs =", value, "shippedPcs");
            return (Criteria) this;
        }

        public Criteria andShippedPcsNotEqualTo(Integer value) {
            addCriterion("shipped_pcs <>", value, "shippedPcs");
            return (Criteria) this;
        }

        public Criteria andShippedPcsGreaterThan(Integer value) {
            addCriterion("shipped_pcs >", value, "shippedPcs");
            return (Criteria) this;
        }

        public Criteria andShippedPcsGreaterThanOrEqualTo(Integer value) {
            addCriterion("shipped_pcs >=", value, "shippedPcs");
            return (Criteria) this;
        }

        public Criteria andShippedPcsLessThan(Integer value) {
            addCriterion("shipped_pcs <", value, "shippedPcs");
            return (Criteria) this;
        }

        public Criteria andShippedPcsLessThanOrEqualTo(Integer value) {
            addCriterion("shipped_pcs <=", value, "shippedPcs");
            return (Criteria) this;
        }

        public Criteria andShippedPcsIn(List<Integer> values) {
            addCriterion("shipped_pcs in", values, "shippedPcs");
            return (Criteria) this;
        }

        public Criteria andShippedPcsNotIn(List<Integer> values) {
            addCriterion("shipped_pcs not in", values, "shippedPcs");
            return (Criteria) this;
        }

        public Criteria andShippedPcsBetween(Integer value1, Integer value2) {
            addCriterion("shipped_pcs between", value1, value2, "shippedPcs");
            return (Criteria) this;
        }

        public Criteria andShippedPcsNotBetween(Integer value1, Integer value2) {
            addCriterion("shipped_pcs not between", value1, value2, "shippedPcs");
            return (Criteria) this;
        }

        public Criteria andShippedGwIsNull() {
            addCriterion("shipped_gw is null");
            return (Criteria) this;
        }

        public Criteria andShippedGwIsNotNull() {
            addCriterion("shipped_gw is not null");
            return (Criteria) this;
        }

        public Criteria andShippedGwEqualTo(BigDecimal value) {
            addCriterion("shipped_gw =", value, "shippedGw");
            return (Criteria) this;
        }

        public Criteria andShippedGwNotEqualTo(BigDecimal value) {
            addCriterion("shipped_gw <>", value, "shippedGw");
            return (Criteria) this;
        }

        public Criteria andShippedGwGreaterThan(BigDecimal value) {
            addCriterion("shipped_gw >", value, "shippedGw");
            return (Criteria) this;
        }

        public Criteria andShippedGwGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("shipped_gw >=", value, "shippedGw");
            return (Criteria) this;
        }

        public Criteria andShippedGwLessThan(BigDecimal value) {
            addCriterion("shipped_gw <", value, "shippedGw");
            return (Criteria) this;
        }

        public Criteria andShippedGwLessThanOrEqualTo(BigDecimal value) {
            addCriterion("shipped_gw <=", value, "shippedGw");
            return (Criteria) this;
        }

        public Criteria andShippedGwIn(List<BigDecimal> values) {
            addCriterion("shipped_gw in", values, "shippedGw");
            return (Criteria) this;
        }

        public Criteria andShippedGwNotIn(List<BigDecimal> values) {
            addCriterion("shipped_gw not in", values, "shippedGw");
            return (Criteria) this;
        }

        public Criteria andShippedGwBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shipped_gw between", value1, value2, "shippedGw");
            return (Criteria) this;
        }

        public Criteria andShippedGwNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shipped_gw not between", value1, value2, "shippedGw");
            return (Criteria) this;
        }

        public Criteria andShippedVolumeIsNull() {
            addCriterion("shipped_volume is null");
            return (Criteria) this;
        }

        public Criteria andShippedVolumeIsNotNull() {
            addCriterion("shipped_volume is not null");
            return (Criteria) this;
        }

        public Criteria andShippedVolumeEqualTo(BigDecimal value) {
            addCriterion("shipped_volume =", value, "shippedVolume");
            return (Criteria) this;
        }

        public Criteria andShippedVolumeNotEqualTo(BigDecimal value) {
            addCriterion("shipped_volume <>", value, "shippedVolume");
            return (Criteria) this;
        }

        public Criteria andShippedVolumeGreaterThan(BigDecimal value) {
            addCriterion("shipped_volume >", value, "shippedVolume");
            return (Criteria) this;
        }

        public Criteria andShippedVolumeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("shipped_volume >=", value, "shippedVolume");
            return (Criteria) this;
        }

        public Criteria andShippedVolumeLessThan(BigDecimal value) {
            addCriterion("shipped_volume <", value, "shippedVolume");
            return (Criteria) this;
        }

        public Criteria andShippedVolumeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("shipped_volume <=", value, "shippedVolume");
            return (Criteria) this;
        }

        public Criteria andShippedVolumeIn(List<BigDecimal> values) {
            addCriterion("shipped_volume in", values, "shippedVolume");
            return (Criteria) this;
        }

        public Criteria andShippedVolumeNotIn(List<BigDecimal> values) {
            addCriterion("shipped_volume not in", values, "shippedVolume");
            return (Criteria) this;
        }

        public Criteria andShippedVolumeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shipped_volume between", value1, value2, "shippedVolume");
            return (Criteria) this;
        }

        public Criteria andShippedVolumeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shipped_volume not between", value1, value2, "shippedVolume");
            return (Criteria) this;
        }

        public Criteria andCustomsMerchNoIsNull() {
            addCriterion("customs_merch_no is null");
            return (Criteria) this;
        }

        public Criteria andCustomsMerchNoIsNotNull() {
            addCriterion("customs_merch_no is not null");
            return (Criteria) this;
        }

        public Criteria andCustomsMerchNoEqualTo(String value) {
            addCriterion("customs_merch_no =", value, "customsMerchNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMerchNoNotEqualTo(String value) {
            addCriterion("customs_merch_no <>", value, "customsMerchNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMerchNoGreaterThan(String value) {
            addCriterion("customs_merch_no >", value, "customsMerchNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMerchNoGreaterThanOrEqualTo(String value) {
            addCriterion("customs_merch_no >=", value, "customsMerchNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMerchNoLessThan(String value) {
            addCriterion("customs_merch_no <", value, "customsMerchNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMerchNoLessThanOrEqualTo(String value) {
            addCriterion("customs_merch_no <=", value, "customsMerchNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMerchNoLike(String value) {
            addCriterion("customs_merch_no like", value, "customsMerchNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMerchNoNotLike(String value) {
            addCriterion("customs_merch_no not like", value, "customsMerchNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMerchNoIn(List<String> values) {
            addCriterion("customs_merch_no in", values, "customsMerchNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMerchNoNotIn(List<String> values) {
            addCriterion("customs_merch_no not in", values, "customsMerchNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMerchNoBetween(String value1, String value2) {
            addCriterion("customs_merch_no between", value1, value2, "customsMerchNo");
            return (Criteria) this;
        }

        public Criteria andCustomsMerchNoNotBetween(String value1, String value2) {
            addCriterion("customs_merch_no not between", value1, value2, "customsMerchNo");
            return (Criteria) this;
        }

        public Criteria andMerchNameIsNull() {
            addCriterion("merch_name is null");
            return (Criteria) this;
        }

        public Criteria andMerchNameIsNotNull() {
            addCriterion("merch_name is not null");
            return (Criteria) this;
        }

        public Criteria andMerchNameEqualTo(String value) {
            addCriterion("merch_name =", value, "merchName");
            return (Criteria) this;
        }

        public Criteria andMerchNameNotEqualTo(String value) {
            addCriterion("merch_name <>", value, "merchName");
            return (Criteria) this;
        }

        public Criteria andMerchNameGreaterThan(String value) {
            addCriterion("merch_name >", value, "merchName");
            return (Criteria) this;
        }

        public Criteria andMerchNameGreaterThanOrEqualTo(String value) {
            addCriterion("merch_name >=", value, "merchName");
            return (Criteria) this;
        }

        public Criteria andMerchNameLessThan(String value) {
            addCriterion("merch_name <", value, "merchName");
            return (Criteria) this;
        }

        public Criteria andMerchNameLessThanOrEqualTo(String value) {
            addCriterion("merch_name <=", value, "merchName");
            return (Criteria) this;
        }

        public Criteria andMerchNameLike(String value) {
            addCriterion("merch_name like", value, "merchName");
            return (Criteria) this;
        }

        public Criteria andMerchNameNotLike(String value) {
            addCriterion("merch_name not like", value, "merchName");
            return (Criteria) this;
        }

        public Criteria andMerchNameIn(List<String> values) {
            addCriterion("merch_name in", values, "merchName");
            return (Criteria) this;
        }

        public Criteria andMerchNameNotIn(List<String> values) {
            addCriterion("merch_name not in", values, "merchName");
            return (Criteria) this;
        }

        public Criteria andMerchNameBetween(String value1, String value2) {
            addCriterion("merch_name between", value1, value2, "merchName");
            return (Criteria) this;
        }

        public Criteria andMerchNameNotBetween(String value1, String value2) {
            addCriterion("merch_name not between", value1, value2, "merchName");
            return (Criteria) this;
        }

        public Criteria andDeclaCountIsNull() {
            addCriterion("decla_count is null");
            return (Criteria) this;
        }

        public Criteria andDeclaCountIsNotNull() {
            addCriterion("decla_count is not null");
            return (Criteria) this;
        }

        public Criteria andDeclaCountEqualTo(Integer value) {
            addCriterion("decla_count =", value, "declaCount");
            return (Criteria) this;
        }

        public Criteria andDeclaCountNotEqualTo(Integer value) {
            addCriterion("decla_count <>", value, "declaCount");
            return (Criteria) this;
        }

        public Criteria andDeclaCountGreaterThan(Integer value) {
            addCriterion("decla_count >", value, "declaCount");
            return (Criteria) this;
        }

        public Criteria andDeclaCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("decla_count >=", value, "declaCount");
            return (Criteria) this;
        }

        public Criteria andDeclaCountLessThan(Integer value) {
            addCriterion("decla_count <", value, "declaCount");
            return (Criteria) this;
        }

        public Criteria andDeclaCountLessThanOrEqualTo(Integer value) {
            addCriterion("decla_count <=", value, "declaCount");
            return (Criteria) this;
        }

        public Criteria andDeclaCountIn(List<Integer> values) {
            addCriterion("decla_count in", values, "declaCount");
            return (Criteria) this;
        }

        public Criteria andDeclaCountNotIn(List<Integer> values) {
            addCriterion("decla_count not in", values, "declaCount");
            return (Criteria) this;
        }

        public Criteria andDeclaCountBetween(Integer value1, Integer value2) {
            addCriterion("decla_count between", value1, value2, "declaCount");
            return (Criteria) this;
        }

        public Criteria andDeclaCountNotBetween(Integer value1, Integer value2) {
            addCriterion("decla_count not between", value1, value2, "declaCount");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitIsNull() {
            addCriterion("decla_unit is null");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitIsNotNull() {
            addCriterion("decla_unit is not null");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitEqualTo(String value) {
            addCriterion("decla_unit =", value, "declaUnit");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitNotEqualTo(String value) {
            addCriterion("decla_unit <>", value, "declaUnit");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitGreaterThan(String value) {
            addCriterion("decla_unit >", value, "declaUnit");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitGreaterThanOrEqualTo(String value) {
            addCriterion("decla_unit >=", value, "declaUnit");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitLessThan(String value) {
            addCriterion("decla_unit <", value, "declaUnit");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitLessThanOrEqualTo(String value) {
            addCriterion("decla_unit <=", value, "declaUnit");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitLike(String value) {
            addCriterion("decla_unit like", value, "declaUnit");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitNotLike(String value) {
            addCriterion("decla_unit not like", value, "declaUnit");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitIn(List<String> values) {
            addCriterion("decla_unit in", values, "declaUnit");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitNotIn(List<String> values) {
            addCriterion("decla_unit not in", values, "declaUnit");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitBetween(String value1, String value2) {
            addCriterion("decla_unit between", value1, value2, "declaUnit");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitNotBetween(String value1, String value2) {
            addCriterion("decla_unit not between", value1, value2, "declaUnit");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitPriceIsNull() {
            addCriterion("decla_unit_price is null");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitPriceIsNotNull() {
            addCriterion("decla_unit_price is not null");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitPriceEqualTo(BigDecimal value) {
            addCriterion("decla_unit_price =", value, "declaUnitPrice");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitPriceNotEqualTo(BigDecimal value) {
            addCriterion("decla_unit_price <>", value, "declaUnitPrice");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitPriceGreaterThan(BigDecimal value) {
            addCriterion("decla_unit_price >", value, "declaUnitPrice");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("decla_unit_price >=", value, "declaUnitPrice");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitPriceLessThan(BigDecimal value) {
            addCriterion("decla_unit_price <", value, "declaUnitPrice");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("decla_unit_price <=", value, "declaUnitPrice");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitPriceIn(List<BigDecimal> values) {
            addCriterion("decla_unit_price in", values, "declaUnitPrice");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitPriceNotIn(List<BigDecimal> values) {
            addCriterion("decla_unit_price not in", values, "declaUnitPrice");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("decla_unit_price between", value1, value2, "declaUnitPrice");
            return (Criteria) this;
        }

        public Criteria andDeclaUnitPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("decla_unit_price not between", value1, value2, "declaUnitPrice");
            return (Criteria) this;
        }

        public Criteria andDeclaTotalPriceIsNull() {
            addCriterion("decla_total_price is null");
            return (Criteria) this;
        }

        public Criteria andDeclaTotalPriceIsNotNull() {
            addCriterion("decla_total_price is not null");
            return (Criteria) this;
        }

        public Criteria andDeclaTotalPriceEqualTo(BigDecimal value) {
            addCriterion("decla_total_price =", value, "declaTotalPrice");
            return (Criteria) this;
        }

        public Criteria andDeclaTotalPriceNotEqualTo(BigDecimal value) {
            addCriterion("decla_total_price <>", value, "declaTotalPrice");
            return (Criteria) this;
        }

        public Criteria andDeclaTotalPriceGreaterThan(BigDecimal value) {
            addCriterion("decla_total_price >", value, "declaTotalPrice");
            return (Criteria) this;
        }

        public Criteria andDeclaTotalPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("decla_total_price >=", value, "declaTotalPrice");
            return (Criteria) this;
        }

        public Criteria andDeclaTotalPriceLessThan(BigDecimal value) {
            addCriterion("decla_total_price <", value, "declaTotalPrice");
            return (Criteria) this;
        }

        public Criteria andDeclaTotalPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("decla_total_price <=", value, "declaTotalPrice");
            return (Criteria) this;
        }

        public Criteria andDeclaTotalPriceIn(List<BigDecimal> values) {
            addCriterion("decla_total_price in", values, "declaTotalPrice");
            return (Criteria) this;
        }

        public Criteria andDeclaTotalPriceNotIn(List<BigDecimal> values) {
            addCriterion("decla_total_price not in", values, "declaTotalPrice");
            return (Criteria) this;
        }

        public Criteria andDeclaTotalPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("decla_total_price between", value1, value2, "declaTotalPrice");
            return (Criteria) this;
        }

        public Criteria andDeclaTotalPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("decla_total_price not between", value1, value2, "declaTotalPrice");
            return (Criteria) this;
        }

        public Criteria andDeclaCurrencyIsNull() {
            addCriterion("decla_currency is null");
            return (Criteria) this;
        }

        public Criteria andDeclaCurrencyIsNotNull() {
            addCriterion("decla_currency is not null");
            return (Criteria) this;
        }

        public Criteria andDeclaCurrencyEqualTo(String value) {
            addCriterion("decla_currency =", value, "declaCurrency");
            return (Criteria) this;
        }

        public Criteria andDeclaCurrencyNotEqualTo(String value) {
            addCriterion("decla_currency <>", value, "declaCurrency");
            return (Criteria) this;
        }

        public Criteria andDeclaCurrencyGreaterThan(String value) {
            addCriterion("decla_currency >", value, "declaCurrency");
            return (Criteria) this;
        }

        public Criteria andDeclaCurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("decla_currency >=", value, "declaCurrency");
            return (Criteria) this;
        }

        public Criteria andDeclaCurrencyLessThan(String value) {
            addCriterion("decla_currency <", value, "declaCurrency");
            return (Criteria) this;
        }

        public Criteria andDeclaCurrencyLessThanOrEqualTo(String value) {
            addCriterion("decla_currency <=", value, "declaCurrency");
            return (Criteria) this;
        }

        public Criteria andDeclaCurrencyLike(String value) {
            addCriterion("decla_currency like", value, "declaCurrency");
            return (Criteria) this;
        }

        public Criteria andDeclaCurrencyNotLike(String value) {
            addCriterion("decla_currency not like", value, "declaCurrency");
            return (Criteria) this;
        }

        public Criteria andDeclaCurrencyIn(List<String> values) {
            addCriterion("decla_currency in", values, "declaCurrency");
            return (Criteria) this;
        }

        public Criteria andDeclaCurrencyNotIn(List<String> values) {
            addCriterion("decla_currency not in", values, "declaCurrency");
            return (Criteria) this;
        }

        public Criteria andDeclaCurrencyBetween(String value1, String value2) {
            addCriterion("decla_currency between", value1, value2, "declaCurrency");
            return (Criteria) this;
        }

        public Criteria andDeclaCurrencyNotBetween(String value1, String value2) {
            addCriterion("decla_currency not between", value1, value2, "declaCurrency");
            return (Criteria) this;
        }

        public Criteria andOriginCountryIsNull() {
            addCriterion("origin_country is null");
            return (Criteria) this;
        }

        public Criteria andOriginCountryIsNotNull() {
            addCriterion("origin_country is not null");
            return (Criteria) this;
        }

        public Criteria andOriginCountryEqualTo(String value) {
            addCriterion("origin_country =", value, "originCountry");
            return (Criteria) this;
        }

        public Criteria andOriginCountryNotEqualTo(String value) {
            addCriterion("origin_country <>", value, "originCountry");
            return (Criteria) this;
        }

        public Criteria andOriginCountryGreaterThan(String value) {
            addCriterion("origin_country >", value, "originCountry");
            return (Criteria) this;
        }

        public Criteria andOriginCountryGreaterThanOrEqualTo(String value) {
            addCriterion("origin_country >=", value, "originCountry");
            return (Criteria) this;
        }

        public Criteria andOriginCountryLessThan(String value) {
            addCriterion("origin_country <", value, "originCountry");
            return (Criteria) this;
        }

        public Criteria andOriginCountryLessThanOrEqualTo(String value) {
            addCriterion("origin_country <=", value, "originCountry");
            return (Criteria) this;
        }

        public Criteria andOriginCountryLike(String value) {
            addCriterion("origin_country like", value, "originCountry");
            return (Criteria) this;
        }

        public Criteria andOriginCountryNotLike(String value) {
            addCriterion("origin_country not like", value, "originCountry");
            return (Criteria) this;
        }

        public Criteria andOriginCountryIn(List<String> values) {
            addCriterion("origin_country in", values, "originCountry");
            return (Criteria) this;
        }

        public Criteria andOriginCountryNotIn(List<String> values) {
            addCriterion("origin_country not in", values, "originCountry");
            return (Criteria) this;
        }

        public Criteria andOriginCountryBetween(String value1, String value2) {
            addCriterion("origin_country between", value1, value2, "originCountry");
            return (Criteria) this;
        }

        public Criteria andOriginCountryNotBetween(String value1, String value2) {
            addCriterion("origin_country not between", value1, value2, "originCountry");
            return (Criteria) this;
        }

        public Criteria andDestCountryIsNull() {
            addCriterion("dest_country is null");
            return (Criteria) this;
        }

        public Criteria andDestCountryIsNotNull() {
            addCriterion("dest_country is not null");
            return (Criteria) this;
        }

        public Criteria andDestCountryEqualTo(String value) {
            addCriterion("dest_country =", value, "destCountry");
            return (Criteria) this;
        }

        public Criteria andDestCountryNotEqualTo(String value) {
            addCriterion("dest_country <>", value, "destCountry");
            return (Criteria) this;
        }

        public Criteria andDestCountryGreaterThan(String value) {
            addCriterion("dest_country >", value, "destCountry");
            return (Criteria) this;
        }

        public Criteria andDestCountryGreaterThanOrEqualTo(String value) {
            addCriterion("dest_country >=", value, "destCountry");
            return (Criteria) this;
        }

        public Criteria andDestCountryLessThan(String value) {
            addCriterion("dest_country <", value, "destCountry");
            return (Criteria) this;
        }

        public Criteria andDestCountryLessThanOrEqualTo(String value) {
            addCriterion("dest_country <=", value, "destCountry");
            return (Criteria) this;
        }

        public Criteria andDestCountryLike(String value) {
            addCriterion("dest_country like", value, "destCountry");
            return (Criteria) this;
        }

        public Criteria andDestCountryNotLike(String value) {
            addCriterion("dest_country not like", value, "destCountry");
            return (Criteria) this;
        }

        public Criteria andDestCountryIn(List<String> values) {
            addCriterion("dest_country in", values, "destCountry");
            return (Criteria) this;
        }

        public Criteria andDestCountryNotIn(List<String> values) {
            addCriterion("dest_country not in", values, "destCountry");
            return (Criteria) this;
        }

        public Criteria andDestCountryBetween(String value1, String value2) {
            addCriterion("dest_country between", value1, value2, "destCountry");
            return (Criteria) this;
        }

        public Criteria andDestCountryNotBetween(String value1, String value2) {
            addCriterion("dest_country not between", value1, value2, "destCountry");
            return (Criteria) this;
        }

        public Criteria andSupervisionConditionsIsNull() {
            addCriterion("supervision_conditions is null");
            return (Criteria) this;
        }

        public Criteria andSupervisionConditionsIsNotNull() {
            addCriterion("supervision_conditions is not null");
            return (Criteria) this;
        }

        public Criteria andSupervisionConditionsEqualTo(String value) {
            addCriterion("supervision_conditions =", value, "supervisionConditions");
            return (Criteria) this;
        }

        public Criteria andSupervisionConditionsNotEqualTo(String value) {
            addCriterion("supervision_conditions <>", value, "supervisionConditions");
            return (Criteria) this;
        }

        public Criteria andSupervisionConditionsGreaterThan(String value) {
            addCriterion("supervision_conditions >", value, "supervisionConditions");
            return (Criteria) this;
        }

        public Criteria andSupervisionConditionsGreaterThanOrEqualTo(String value) {
            addCriterion("supervision_conditions >=", value, "supervisionConditions");
            return (Criteria) this;
        }

        public Criteria andSupervisionConditionsLessThan(String value) {
            addCriterion("supervision_conditions <", value, "supervisionConditions");
            return (Criteria) this;
        }

        public Criteria andSupervisionConditionsLessThanOrEqualTo(String value) {
            addCriterion("supervision_conditions <=", value, "supervisionConditions");
            return (Criteria) this;
        }

        public Criteria andSupervisionConditionsLike(String value) {
            addCriterion("supervision_conditions like", value, "supervisionConditions");
            return (Criteria) this;
        }

        public Criteria andSupervisionConditionsNotLike(String value) {
            addCriterion("supervision_conditions not like", value, "supervisionConditions");
            return (Criteria) this;
        }

        public Criteria andSupervisionConditionsIn(List<String> values) {
            addCriterion("supervision_conditions in", values, "supervisionConditions");
            return (Criteria) this;
        }

        public Criteria andSupervisionConditionsNotIn(List<String> values) {
            addCriterion("supervision_conditions not in", values, "supervisionConditions");
            return (Criteria) this;
        }

        public Criteria andSupervisionConditionsBetween(String value1, String value2) {
            addCriterion("supervision_conditions between", value1, value2, "supervisionConditions");
            return (Criteria) this;
        }

        public Criteria andSupervisionConditionsNotBetween(String value1, String value2) {
            addCriterion("supervision_conditions not between", value1, value2, "supervisionConditions");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：shipped_info
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 
     * Criterion
     * 数据库表：shipped_info
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}